# Generated by Django 6.0.3 on 2026-04-09 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfessional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_id', models.CharField(db_index=True, editable=False, help_text='Auto generated as HP-{license_number}', max_length=30, unique=True)),
                ('license_number', models.CharField(db_index=True, help_text='Official medical license number', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('specialization', models.CharField(choices=[('general_medicine', 'General Medicine'), ('mental_health', 'Mental Health'), ('surgery', 'Surgery'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('dermatology', 'Dermatology'), ('gynecology', 'Gynecology'), ('laboratory', 'Laboratory'), ('other', 'Other')], db_index=True, max_length=50)),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_professionals', to='hospitals.hospital')),
                ('registered_by', models.ForeignKey(help_text='Admin who registered this health professional', on_delete=django.db.models.deletion.PROTECT, related_name='registered_health_professionals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_professional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Professional',
                'verbose_name_plural': 'Health Professionals',
                'db_table': 'health_professionals',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='health_prof_full_na_4ad64e_idx'), models.Index(fields=['specialization'], name='health_prof_special_775af6_idx'), models.Index(fields=['hospital'], name='health_prof_hospita_fb5099_idx'), models.Index(fields=['department'], name='health_prof_departm_109e88_idx'), models.Index(fields=['is_active'], name='health_prof_is_acti_ae6c1c_idx')],
            },
        ),
    ]
