# Generated by Django 6.0.3 on 2026-04-09 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospital_id', models.CharField(db_index=True, editable=False, help_text='Human readable ID — auto generated as HOSP-{registration_number}', max_length=30, unique=True)),
                ('registration_number', models.CharField(db_index=True, help_text='Official government registration number', max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('central_hospital', 'Central Hospital'), ('district_hospital', 'District Hospital'), ('rural_hospital', 'Rural Hospital'), ('health_center', 'Health Center'), ('clinic', 'Clinic')], db_index=True, max_length=50)),
                ('district', models.CharField(db_index=True, max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('cpr_institution_id', models.UUIDField(blank=True, help_text='UUID assigned by CPR when this hospital registered as an institution', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created this hospital', on_delete=django.db.models.deletion.PROTECT, related_name='created_hospitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'db_table': 'hospitals',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='hospitals_name_9e93ed_idx'), models.Index(fields=['category'], name='hospitals_categor_a69e21_idx'), models.Index(fields=['district'], name='hospitals_distric_acad89_idx'), models.Index(fields=['is_active'], name='hospitals_is_acti_ff4c80_idx')],
            },
        ),
    ]
